### ISSUE TITLE
Support TextResource abstraction.

### ISSUE THREAD

**Issue by RomanZhilich** [noveogroup/android-check#1]
Gradle now uses [TextResouce](http://www.gradle.org/docs/2.2/dsl/org.gradle.api.resources.TextResource.html) to ease config management.
As http://www.gradle.org/docs/2.2/release-notes#sharing-configuration-files-across-builds suggests, checkstyle plugin already supports it.

Please avoid explicit usage of File for static analyzers configs.

**Comment by igelgrun** [comment]
Supported in 1.1.0.

**Comment by igelgrun** [comment]
Unfortunately, [TextResouce](http://www.gradle.org/docs/2.2/dsl/org.gradle.api.resources.TextResource.html) are [incubating](http://gradle.org/docs/2.2/userguide/feature_lifecycle.html) feature so we should support explicit usage of File for configurations.
