### ISSUE TITLE
Change output folder reports

### ISSUE THREAD

**Issue by aegis123** [noveogroup/android-check#10]
Could you change the output folder for the reports to /project/module/build/reports/{lint, checkstyle, pmd} cause no it goes to /root_project/module/build/outputs/ and the unit tests go to /project/module/build/reports/ and are automatically picked up by the gradle plugin build-dashboard

**Comment by jaredsburrows** [comment]
+1

**Comment by igelgrun** [comment]
Now in version 1.2.1 you can specify output folder and/or files using `report`, `reportXML` and `reportHTML` configuration properties.
