### ISSUE TITLE
Upgrade checkstyle?

### ISSUE THREAD

**Issue by damianflannery** [noveogroup/android-check#24]
CatchParameterName and SuppressionFilter are not supported in the checkstyle version declared in this project (6.10.1). 
https://github.com/noveogroup/android-check/blob/master/android-check-plugin/build.gradle#L10

The latest version of checkstyle is 6.19.

Is it possible to upgrade?

**Comment by MatFl** [comment]
You can do that on your own:

```
classpath('com.noveogroup.android:check:1.2.3') {
     exclude module: 'checkstyle'
}
classpath 'com.puppycrawl.tools:checkstyle:6.19'
```

**Comment by smalichenko** [comment]
Checkstyle has been updated to 7.6.1 version in 1.2.4 android-check release.
