### ISSUE TITLE
Gradle deprecation warning for Task.leftShift()

### ISSUE THREAD

**Issue by FriedrichFroebel** [noveogroup/android-check#32]
Running the checks invokes a deprecation message from Gradle:

> The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.

**Comment by mlagerberg** [comment]
PR #34 should solve this issue

**Comment by Dushistov** [comment]
It would be great to resolve this issue before new version of gradle wil appear.

**Comment by misa** [comment]
Any progress?

**Comment by smalichenko** [comment]
Merged in #34
