### ISSUE TITLE
Take config rootProject.file('config/..) into account

### ISSUE THREAD

**Issue by RomanZhilich** [noveogroup/android-check#5]
As of now, plugin only check current project folder for available config files. It'll be nice to have one configuration for all sub projects.
Ideally root and sub project configurations should be merged automatically.

**Comment by marcoRS** [comment]
:+1:

**Comment by igelgrun** [comment]
Now plugin takes into account `<rootProject>/config/` folder before `<rootProject>/app/config/`.
