### ISSUE TITLE
Findbugs support

### ISSUE THREAD

**Issue by ghost** [noveogroup/android-check#6]
Hi there, do you have any plans to also include support for Findbugs?

**Comment by igelgrun** [comment]
Hello,

Yes, it will be in one of the next releases.

**Comment by ghost** [comment]
Mind if I ask for any ETA or Roadmap?

**Comment by igelgrun** [comment]
Yes, it may be done in few days, but ...
The problem is to execute FindBugs task programmatically.

**Comment by jaredsburrows** [comment]
+1

**Comment by aegis123** [comment]
Any ETA on this?

**Comment by akhy** [comment]
+1

**Comment by vbauer** [comment]
:+1:

**Comment by igelgrun** [comment]
FindBugs is now supported by new 1.2.0 version.
