### ISSUE TITLE
Checkstyle excluding files or directory

### ISSUE THREAD

**Issue by marcoRS** [noveogroup/android-check#8]
How would one go about excluding a specific file directory in Checkstyle? Is it also possible to specify the Checkstyle version ?

**Comment by igelgrun** [comment]
Sorry for long delay, are the questions still actual?

> How would one go about excluding a specific file directory in Checkstyle?

Do you mean to exclude some specific directory from sources analyzed by Checkstyle?

> Is it also possible to specify the Checkstyle version ?

To change Checkstyle version:

```
buildscript {
    repositories { jcenter(); mavenLocal() }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'
        classpath('com.puppycrawl.tools:checkstyle:6.1.1') {
            exclude module: 'guava'
        }
        classpath('com.noveogroup.android:check:1.2.0') {
            exclude module: 'checkstyle'
        }
    }
}
```

Unfortunately, plugin doesn't support all versions of Checkstyle.
