### ISSUE TITLE
PMD: build log is getting bloated with warnings

### ISSUE THREAD

**Issue by RomanZhilich** [noveogroup/android-check#9]
I've got a whole bunch of following messages during build:
`[ant:null] Removed misconfigured rule: LoosePackageCoupling  cause: No packages or classes specified`

Apparently this is caused by misconfigured PMD rule, maybe due to the fact that `ant` property is null [here](https://github.com/noveogroup/android-check/blob/05f50c19022b9bf4aeeec5501ade170257dc82d2/android-check-plugin/src/main/groovy/com/noveogroup/android/check/pmd/PmdCheck.groovy#L57).

**Comment by igelgrun** [comment]
Fixed in 01afa8097cb30b02f32ba46e46239655bbebd04c.
Release will be published soon.

**Comment by dglynch** [comment]
It looks like the above fix has not yet made it into a published release. I am currently using version 1.2.3 and that seems to be the latest version available. Is there any update on this issue? Thanks!

**Comment by smalichenko** [comment]
Released in 1.2.4 version.
